feat: DAMD-137 (proper motion and parallax in pfsDesign and pfsConfig)
Subaru-PFS/datamodel pull request #117
Opened 2023-07-17 02:02 UTC by monodera

- Add `epoch`, `pmRa`, `pmDec`, and `parallax` for targets in the DESIGN table of pfsDesign and pfsConfig with the same formats as those in the GUIDESTAR table.
- Modify `datamodel.txt` and `tests_PfsConfig.py` accordingly.

2023-07-17 14:13 UTC, PaulPrice requested changes
This looks reasonable, but there need to be some changes before merging. In particular, `test_PfsFluxReference.py` fails due to this change, and I'm sure there must be similar failures in drp_stella.

2023-07-17 18:22 UTC, monodera commented on datamodel.txt
> +      epoch          7-digit string
I copied it from the explanation in the guide star table which was written by someone before. It's something like "J2000.0".

2023-07-17 18:26 UTC, PaulPrice commented on datamodel.txt
> +      epoch          7-digit string
I think "7-character string" would be more accurate. "Digit" implies solely numbers.

2023-07-17 18:30 UTC, monodera commented on python/pfs/datamodel/pfsConfig.py
> +               "pmDec": "D",
I'll change it to "E".

I actually copied from `guideStars.py` and it also has apparently inconsistent definitions (at lines around 138).  

```
            Column("pmRa", "D", array=self.pmRa, unit='mas/year'),
            Column("pmDec", "D", array=self.pmDec, unit='mas/year'),
            Column("parallax", "E", array=self.parallax, unit='mas'),
```

2023-07-17 18:50 UTC, PaulPrice commented on python/pfs/datamodel/pfsConfig.py
> +               "pmDec": "D",
Would you fix those (in a separate commit) while you're in there, please?

2023-07-17 19:04 UTC, monodera commented on python/pfs/datamodel/pfsConfig.py
> +               "pmDec": "D",
done

2023-07-17 19:05 UTC, monodera commented
I fixed `test_PfsFluxReference.py`, but not those for `drp_stella`.

2023-07-17 19:14 UTC, PaulPrice commented
They will need to be fixed before merging.

2023-07-17 20:53 UTC, PaulPrice commented
The best way would be to run the tests (`setup -jr . ` and then `scons`) and fix anything that fails. Alternatively, you could `grep` for the `PfsConfig` constructor.

2023-07-18 03:50 UTC, monodera commented
I did the test and made modifications accordingly. The corresponding PRs have been made in `drp_stella`.

2023-07-25 04:09 UTC, merged