feat: DAMD-146 (add proposal_id and ob_code to pfsDesign/pfsConfig fi…
Subaru-PFS/datamodel pull request #118
Opened 2023-07-17 02:31 UTC by monodera

…les)

- `proposalId` and `obCode` are added.
- `datamodel.txt` and `test_PfsConfig.py` are modified accordingly.

2023-07-17 14:21 UTC, PaulPrice requested changes
`test_PfsFluxReference.py` fails due to this change, and I'm sure there are similar tests in drp_stella that fail too.

2023-07-17 14:21 UTC, PaulPrice commented on datamodel.txt
> +      obCode         string
Please add more explanation of these below.

2023-07-17 14:21 UTC, PaulPrice commented on python/pfs/datamodel/pfsConfig.py
> +        OB code of each fiber.
Spell out OB: "Observing block".

2023-09-05 18:46 UTC, PaulPrice commented
Please squash related changes, and use `git rebase` instead of merging `master` into the ticket branch.

2023-09-06 19:47 UTC, monodera commented
I think that I have squashed everything suggested by `git rebase` in this and the other related repositories. I've also run the integration test locally and succeeded.

2023-09-06 19:52 UTC, PaulPrice commented
The current state is a bit of a mess, with multiple commits with the same title.

2023-09-06 20:26 UTC, monodera commented
What can I do from now to clean up thing?

2023-09-06 20:32 UTC, PaulPrice commented
If you're at NAOJ, perhaps @SogoMineo is able to help guide you through the git labyrinth?

2023-09-06 20:45 UTC, monodera commented
we are in different branches, but I'll ask him.

2023-09-07 04:47 UTC, monodera commented
With the great help of @SogoMineo, I restarted editing from the current master branch and force-pushed the commits as shown in the tree. 

A few places differ from the older commits, but these lines are duplicates from my wrong edit in the previous rebase.  You can expand the code and find the identical lines a few lines below the removed ones.

2023-09-07 13:45 UTC, PaulPrice approved these changes
Very nice. Thank you, @SogoMineo! And thank you @monodera for bearing with me.

2023-09-14 02:49 UTC, monodera commented
Can I merge to the master or you will merge, @PaulPrice ?

2023-09-14 03:10 UTC, monodera commented
@SogoMineo told me that I can push the green "merge pull request" button as encouraged in the documentation, so I'll do it.

2023-09-14 20:52 UTC, monodera commented
@PaulPrice When merging a PR, which method should I use from the menu, "Create a merge commit", "Squash and merge", and "Rebase and merge"?

Also, could you please take a look at these related branches in `drp_stella` and `pfs_utils`?
https://github.com/Subaru-PFS/drp_stella/pull/330
https://github.com/Subaru-PFS/pfs_utils/pull/65

2023-09-14 21:02 UTC, PaulPrice commented
Please use the "Create a merge commit" method.
The others look fine too.
You've run these through the integration test, right?

2023-09-14 21:12 UTC, monodera commented
Yes, it finished with the "Done with Gen3." message.

2023-09-14 22:08 UTC, merged