DAMD-128: Add implementation of new PfsReference class
Subaru-PFS/datamodel pull request #95
Opened 2022-02-21 02:12 UTC by SogoMineo

The definition of PfsReference is changed so that it will conform to
the revision of datamodel.txt made by DAMD-127 and DAMD-129.

2022-02-22 17:13 UTC, PaulPrice requested changes
We need to make sure this passes the integration test before merging. Currently we can't do that because of a numpy version issue (see below).

2022-02-22 17:13 UTC, PaulPrice commented on tests/test_FileFormats.py
> -
Can you modify this test rather than removing it? It would be very simple, and I'm sure you've covered this case in your own tests, but it's good to have it here with other tests of the same kind.

2022-02-24 00:08 UTC, SogoMineo commented on python/pfs/datamodel/pfsReference.py
> +@inheritDocstrings
I am deleting this decorator. (I used this decorator because `PfsSimpleSpectrum` is decorated in the same manner.)

2022-02-24 03:33 UTC, SogoMineo commented
The new `PfsReference` will break a lot of things in `drp_stella` and `pfs_pipe2d`, but there are not yet a code that is utilizing the new `PfsReference`. Now I don't think it a good idea to revise `PfsReference` here, but I feel I had better rename this new `PfsReference` to something like `PfsFluxReference` and keep the old `PfsReference` until the new flux calibration task is made. If I should do so, should I withdraw this PR and open a fresh one, or should I keep using this PR?

2022-02-24 06:42 UTC, SogoMineo commented
I pushed the redacted version, but it actually breaks `drp_stella` and `pfs_pipe2d`. (See my previous comment).

2022-02-24 14:36 UTC, PaulPrice commented
`PfsFluxReference` sounds fine. We may as well do it here.

2022-02-25 03:04 UTC, SogoMineo commented
I revived the old `PfsReference` and renamed the new one to `PfsFluxReference`. I changed the ccommit message accordingly. The integration test now passes. Please review the change.

2022-02-25 03:17 UTC, PaulPrice approved these changes
Awesome!

2022-02-25 06:31 UTC, SogoMineo commented
I believe that I have now the exact version of astropy that is required.

2022-03-02 00:06 UTC, SogoMineo commented
Can I merge this PR? The changes are approved here in github, but review is not complete in JIRA.

2022-03-02 00:16 UTC, PaulPrice commented
Sorry, that's an oversight.

2022-03-02 00:43 UTC, merged